name: aws tests

on:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - 'lambdas/**'
      
jobs:
  ruff:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
          config: .ruff.toml
          working-directory: lambdas
  
  # for now now build / deploy on github
  tests:
    name: run cloud decoupled tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables from secrets
        run: |
          echo "AWS_PROFILE=${{ secrets.AWS_PROFILE }}" >> $GITHUB_ENV
          echo "APP_NAME_PRIVATE=${{ secrets.APP_NAME_PRIVATE }}" >> $GITHUB_ENV
          echo "SQS_ARN_ROOT=${{ secrets.SQS_ARN_ROOT }}" >> $GITHUB_ENV
          echo "ACCOUNT_ID=${{ secrets.ACCOUNT_ID }}" >> $GITHUB_ENV

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set up AWS CLI with profile
        run: |
          mkdir -p ~/.aws
          echo "[${{ secrets.AWS_PROFILE }}]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[profile ${{ secrets.AWS_PROFILE }}]" > ~/.aws/config
          echo "region = ${{ secrets.AWS_REGION }}" >> ~/.aws/config

      - name: Verify AWS CLI configuration
        run: aws sts get-caller-identity --profile ${{ secrets.AWS_PROFILE }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install -r requirements.test
        working-directory: lambdas

      - name: Run tests
        working-directory: lambdas
        run: | 
          PYTHONPATH=. python3.12 -m pytest tests/test_hello_world.py &&
          PYTHONPATH=. python3.12 -m pytest tests/cloud_decoupled/receivers/test_receiver_start.py &&
          PYTHONPATH=. python3.12 -m pytest tests/cloud_decoupled/receivers/test_receiver_preprocess.py &&
          PYTHONPATH=. python3.12 -m pytest tests/cloud_decoupled/receivers/test_receiver_process.py &&
          PYTHONPATH=. python3.12 -m pytest tests/cloud_decoupled/receivers/test_receiver_end.py &&
          PYTHONPATH=. python3.12 -m pytest tests/cloud_decoupled/receivers/test_receiver_status.py